package com.example.myapplication;

import com.example.myapplication.model.MedicineModel;

import java.util.ArrayList;

public class Info {

    public static ArrayList<MedicineModel> getMedicines() {
        ArrayList<MedicineModel> medicines = new ArrayList<>();
        medicines.add(new MedicineModel("Atorvastatin", R.drawable.pic_m1, "Atorvastatin belongs to a group of medicines called statins. It is used to lower cholesterol if you've been diagnosed with high blood cholesterol and prevent heart disease, including heart attacks and strokes.", "Atorvastatin is used together with a proper diet to lower cholesterol and triglyceride (fats) levels in the blood. This medicine may help prevent medical problems (eg, chest pain, heart attack, or stroke) that are caused by fats clogging the blood vessels.", 100));
        medicines.add(new MedicineModel("Levothyroxine", R.drawable.pic_m2, "Levothyroxine is a medicine used to treat an underactive thyroid gland (hypothyroidism). The thyroid gland makes thyroid hormones which help to control energy levels and growth. Levothyroxine is taken to replace the missing thyroid hormone thyroxine. Levothyroxine is only available on prescription.", "Levothyroxine is a medicine used to treat an underactive thyroid gland (hypothyroidism). The thyroid gland makes thyroid hormones which help to control energy levels and growth. Levothyroxine is taken to replace the missing thyroid hormone thyroxine. Levothyroxine is only available on prescription.", 200));
        medicines.add(new MedicineModel("Metformin", R.drawable.pic_m3, "Metformin is used to treat high blood sugar levels that are caused by a type of diabetes mellitus or sugar diabetes called type 2 diabetes. With this type of diabetes, insulin produced by the pancreas is not able to get sugar into the cells of the body where it can work properly.", "Metformin is used to treat high blood sugar levels that are caused by a type of diabetes mellitus or sugar diabetes called type 2 diabetes. With this type of diabetes, insulin produced by the pancreas is not able to get sugar into the cells of the body where it can work properly.", 300));
        medicines.add(new MedicineModel("Lisinopril", R.drawable.pic_m4, "Lisinopril is used alone or in combination with other medications to treat high blood pressure in adults and children 6 years of age and older. It is used in combination with other medications to treat heart failure. Lisinopril is also used to improve survival after a heart attack.", "Lisinopril is a medicine to treat high blood pressure (hypertension) and heart failure. It's also prescribed after a heart attack and helps prevent future strokes and heart attacks. It also improves your survival if you're taking it after a recent heart attack or for heart failure.", 400));
        medicines.add(new MedicineModel("Amlodipine", R.drawable.pic_m5, "Amlodipine is used alone or together with other medicines to treat hypertension (high blood pressure). High blood pressure adds to the workload of the heart and arteries. If it continues for a long time, the heart and arteries may not function properly.", "Amlodipine is used alone or in combination with other medications to treat high blood pressure in adults and children 6 years and older. It is also used to treat certain types of angina (chest pain) and coronary artery disease (narrowing of the blood vessels that supply blood to the heart).", 500));
        medicines.add(new MedicineModel("Metoprolol", R.drawable.pic_m6, "Metoprolol is used alone or together with other medicines to treat high blood pressure (hypertension). High blood pressure adds to the workload of the heart and arteries. If it continues for a long time, the heart and arteries may not function properly.", "Metoprolol is used alone or together with other medicines to treat high blood pressure (hypertension). High blood pressure adds to the workload of the heart and arteries. If it continues for a long time, the heart and arteries may not function properly.", 600));
        medicines.add(new MedicineModel("Omeprazole", R.drawable.pic_m7, "It's widely used to treat indigestion and heartburn, and acid reflux. It's also taken to prevent and treat stomach ulcers. Omeprazole is a type of medicine called a proton pump inhibitor (PPI). Proton pumps are enzymes in the lining of your stomach that help it make acid to digest food.", "حوالى 3,470,000 نتيجة (0.63 ثانية) \n" +
                "Omeprazole is used to treat certain conditions where there is too much acid in the stomach. It is used to treat gastric and duodenal ulcers, erosive esophagitis, and gastroesophageal reflux disease (GERD). GERD is a condition where the acid in the stomach washes back up into the esophagus.", 700));
        medicines.add(new MedicineModel("Simvastatin", R.drawable.pic_m8, "Simvastatin is used together with a proper diet to treat high cholesterol and triglyceride (fat) levels in the blood. This medicine may help prevent medical problems (eg, heart or blood vessel problems, heart attacks, or strokes) caused by clogged blood vessels.", "Simvastatin is used together with a proper diet to treat high cholesterol and triglyceride (fat) levels in the blood.", 800));
        medicines.add(new MedicineModel("Escitalopram", R.drawable.pic_m9, "Escitalopram is used to treat depression and generalized anxiety disorder (GAD). It is an antidepressant that belongs to a group of medicines known as selective serotonin reuptake inhibitors (SSRIs).", "Escitalopram is used to treat depression and generalized anxiety disorder (GAD). It is an antidepressant that belongs to a group of medicines known as selective serotonin reuptake inhibitors (SSRIs).", 900));
        medicines.add(new MedicineModel("Rosuvastatin", R.drawable.pic_m10, "Rosuvastatin is used together with a proper diet to lower bad cholesterol (LDL) and triglycerides (fats) in the blood, and to increase your good cholesterol (HDL). It is also used to treat adults who cannot control their cholesterol levels by diet and exercise alone.", "Rosuvastatin is used together with diet, weight-loss, and exercise to reduce the risk of heart attack and stroke and to decrease the chance that heart surgery will be needed in people who have heart disease or who are at risk of developing heart disease.", 1000));
        return medicines;
    }
}
